version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
